{
    'name': "TENENET Projekty",

    'summary': "Riadenie projektov, alokácií a reportingu pre TENENET",

    'description': """
Odoo v19 module suite for Tenenet (Slovak NGO).
Manages projects, employee allocations, utilization tracking,
and P&L reporting by program.
    """,

    'author': "Tenenet",
    'website': "https://www.tenenet.sk",

    'category': 'Project',
    'version': '19.0.5.8.1',
    'license': 'LGPL-3',

    'depends': ['base', 'hr', 'hr_holidays', 'hr_skills', 'hr_expense', 'account_reports', 'mail', 'web_enterprise', 'web_gantt', 'web_grid'],


    'assets': {
        'web.assets_backend': [
            'tenenet_projects/static/src/js/tenenet_internal_expense_report_filters.js',
            'tenenet_projects/static/src/js/tenenet_project_yearly_labor_report_filters.js',
            'tenenet_projects/static/src/js/tenenet_cashflow_report_filters.js',
            'tenenet_projects/static/src/js/tenenet_utilization_report_filters.js',
            'tenenet_projects/static/src/js/tenenet_allocation_report_filters.js',
            'tenenet_projects/static/src/js/tenenet_pl_report_filters.js',
            'tenenet_projects/static/src/js/tenenet_employee_list_report_filters.js',
            'tenenet_projects/static/src/js/tenenet_my_timesheets_action.js',
            'tenenet_projects/static/src/js/tenenet_garant_timesheets_action.js',
            'tenenet_projects/static/src/js/timesheet_matrix_host.js',
            'tenenet_projects/static/src/xml/tenenet_internal_expense_report_filters.xml',
            'tenenet_projects/static/src/xml/tenenet_internal_expense_report_line_cell.xml',
            'tenenet_projects/static/src/xml/tenenet_project_yearly_labor_report_filters.xml',
            'tenenet_projects/static/src/xml/tenenet_cashflow_report_filters.xml',
            'tenenet_projects/static/src/xml/tenenet_utilization_report_filters.xml',
            'tenenet_projects/static/src/xml/tenenet_allocation_report_filters.xml',
            'tenenet_projects/static/src/xml/tenenet_pl_report_filters.xml',
            'tenenet_projects/static/src/xml/tenenet_employee_list_report_filters.xml',
            'tenenet_projects/static/src/xml/tenenet_my_timesheets_action.xml',
            'tenenet_projects/static/src/xml/tenenet_garant_timesheets_action.xml',
            'tenenet_projects/static/src/js/tenenet_home_menu_utilization.js',
            'tenenet_projects/static/src/xml/tenenet_home_menu_utilization.xml',
            'tenenet_projects/static/src/xml/hr_holidays_overrides.xml',
            'tenenet_projects/static/src/scss/tenenet_internal_expense_report.scss',
            'tenenet_projects/static/src/scss/tenenet_project_yearly_labor_report.scss',
            'tenenet_projects/static/src/scss/tenenet_cashflow_report.scss',
            'tenenet_projects/static/src/scss/tenenet_utilization_report.scss',
            'tenenet_projects/static/src/scss/tenenet_allocation_report.scss',
            'tenenet_projects/static/src/scss/tenenet_pl_report.scss',
            'tenenet_projects/static/src/scss/tenenet_pl_program_override_grid.scss',
            'tenenet_projects/static/src/scss/timesheet_matrix.scss',
            'tenenet_projects/static/src/scss/tenenet_home_menu_utilization.scss',
            'tenenet_projects/static/src/scss/hr_employee.scss',
        ],
        'web.assets_backend_lazy': [
            'tenenet_projects/static/src/js/cashflow_gantt_view.js',
            'tenenet_projects/static/src/js/tenenet_pl_program_override_grid_view.js',
            'tenenet_projects/static/src/js/tenenet_timesheet_matrix_grid_view.js',
            'tenenet_projects/static/src/xml/cashflow_gantt.xml',
        ],
    },

    'data': [
        'security/tenenet_security.xml',
        'security/tenenet_employee_service_security.xml',
        'security/ir.model.access.csv',
        'data/tenenet_program_data.xml',
        'data/tenenet_donor_data.xml',
        'data/hr_leave_type_data.xml',
        'data/tenenet_alert_mail_template.xml',
        'data/tenenet_alert_cron.xml',
        'data/tenenet_alert_allowed_models_data.xml',
        'views/tenenet_alert_allowed_model_views.xml',
        'views/tenenet_alert_views.xml',
        'views/tenenet_program_views.xml',
        'views/tenenet_project_site_views.xml',
        'views/tenenet_project_contact_views.xml',
        'views/tenenet_donor_views.xml',
        'views/tenenet_project_views.xml',
        'views/tenenet_project_cashflow_views.xml',
        'views/tenenet_cashflow_global_override_views.xml',
        'views/tenenet_pl_program_override_views.xml',
        'views/tenenet_project_milestone_views.xml',
        'views/tenenet_allocation_views.xml',
        'views/tenenet_utilization_views.xml',
        'views/tenenet_project_yearly_labor_report_views.xml',
        'views/tenenet_allocation_report_views.xml',
        'views/tenenet_utilization_report_views.xml',
        'views/tenenet_pl_report_views.xml',
        'views/tenenet_cashflow_report_views.xml',
        'views/tenenet_internal_expense_report_views.xml',
        'views/tenenet_employee_list_report_views.xml',
        'views/tenenet_utilization_sync_wizard_views.xml',
        'views/tenenet_pl_line_views.xml',
        'views/tenenet_project_assignment_views.xml',
        'views/tenenet_project_assignment_wizard_views.xml',
        'views/tenenet_project_assignment_remove_wizard_views.xml',
        'views/tenenet_project_site_wizard_views.xml',
        'views/tenenet_project_contact_wizard_views.xml',
        'views/tenenet_project_milestone_wizard_views.xml',
        'views/tenenet_project_allowed_expense_type_wizard_views.xml',
        'views/tenenet_project_expense_views.xml',
        'views/tenenet_project_receipt_wizard_views.xml',
        'views/tenenet_expense_type_config_views.xml',
        'views/tenenet_project_timesheet_views.xml',
        'views/tenenet_project_timesheet_matrix_views.xml',
        'views/tenenet_employee_tenenet_cost_views.xml',
        'views/tenenet_internal_expense_views.xml',
        'views/res_partner_views.xml',
        'views/tenenet_employee_training_views.xml',
        'views/hr_employee_views.xml',
        'views/menu.xml',
        'views/hr_holidays_overrides.xml',
        'views/hr_expense_views.xml',
        'data/tenenet_sk_holidays_cron.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
}
