from . import test_plan01
from . import test_plan02_project
from . import test_plan03_allocation
from . import test_plan04_utilization
from . import test_plan05_pl_reporting
from . import test_plan08_project_assignment
from . import test_plan09_project_timesheet
from . import test_plan11_utilization_report
from . import test_plan12_project_yearly_labor_report
from . import test_plan13_pl_report
from . import test_plan14_alerts
from . import test_contact_classification
from . import test_employee_availability
from . import test_project_assignment_overlap
from . import test_employee_training
from . import test_employee_service
